// Shared city data for GigSarthi — used across PredictionForm, Dashboard, and AI engine
export const QUICK_CITIES = [
  "Delhi", "Mumbai", "Bangalore", "Hyderabad", "Chennai",
  "Pune", "Kolkata", "Jaipur", "Ahmedabad", "Lucknow",
  "Surat", "Bhopal", "Nagpur", "Indore", "Vadodara",
  "Chandigarh", "Coimbatore", "Kochi", "Visakhapatnam", "Patna",
  "Agra", "Nashik", "Rajkot", "Meerut", "Faridabad",
];

export const CITY_BASE_RATES: Record<string, number> = {
  delhi: 140,
  mumbai: 160,
  bangalore: 150,
  hyderabad: 130,
  chennai: 125,
  pune: 135,
  kolkata: 120,
  jaipur: 115,
  ahmedabad: 120,
  lucknow: 110,
  surat: 118,
  bhopal: 108,
  nagpur: 112,
  indore: 115,
  vadodara: 118,
  chandigarh: 125,
  coimbatore: 115,
  kochi: 130,
  visakhapatnam: 118,
  patna: 100,
  agra: 108,
  nashik: 115,
  rajkot: 110,
  meerut: 105,
  faridabad: 118,
};
